restapp/urls.py
from . import views
from django.urls import path

app_name = 'restapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.index, name='home'),
    path('menu-and-pricing/', views.menu, name='menu'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('24HoursItalianRestaurant/', include('restapp.urls')),
]

restapp/models.py
from django.db import models

# Create your models here.

restapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect


# Create your views here.
from django.urls import reverse


def index(request):
    return render(request, 'restapp/index.html')

def about(request):
    return render(request, 'restapp/about.html')

def contact(request):
    return render(request, 'restapp/contact.html')

def menu(request):
    return render(request, 'restapp/menu.html')

restapp/templates/restapp/about.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/slider.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/zerogrid.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css" media="screen">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
    <script src="{% static 'js/superfish.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/sForm.js' %}"></script>
    <script src="{% static 'js/css3-mediaqueries.js' %}"></script>
</head>
<body>

<!--==============================header=================================-->

<header>
    {% include 'restapp/header.html' %}
</header>


 <div class="main">
<!--=======content================================-->

<div class="content">
  <div class="zerogrid">
  	<div class="row">
    <div class="col-2-5">
	<div class="wrap-col">
      <h2>About Us</h2>
      <img src="{% static 'img/page2_img1.jpg' %}" alt="" class="img_inner">
      <p class="col1">Curabitur in turpisju massa. Donec et nibh non turpis pellentesque suscipit eget. </p>
      <p>Ghfgop Maecnas cursus fringilla sagittis. Donec eu felis purus, iaculis fringilla ipsum. Inte ger non nulla sem, eget volutpat augue. Curabitur in turpisju massa. Donec et nibh non turpis pellentesque suscipit eget.  </p>
      Donec eu felis purus, iaculis fringilla ipsum. Integer non. nulla sem, eget volutpat augue. Curabitur in turpisju massa. Donec et nibh non turpis pellentesque suscipit eget vel odio. Sed tempus orci tempus libero suscipit elementum. Aliquam consectetur. Ghfgop Maecnas cursus.       <br>
      <a href="#" class="btn m1">More</a>
	 </div>
    </div>
	<div class="col-1-5"><div class="wrap-col"><!--empty--></div></div>
    <div class="col-2-5">
	<div class="wrap-col">
      <h2>Testimonials</h2>
      <ul class="testimo">
        <li>
          <blockquote>
            <img src="{% static 'img/page2_img2.png' %}" alt="">
            <div class="extra_wrapper">
              <div class="title">Sara &amp; Kevin <br> Jonson</div>
            </div>
             <div class="clear"></div>
            <p class="col1"><a href="#">Euismod pellentesque in dui. Semper, enim eget eleifend faucibus, sem libero gravida erat, sit amet viverra dui nisl non nulla. Pellentesque in dui euismod.        </a></p>
            <p>Curabitur felis purus, iaculis fringi. ipsum. Integer non nulla sem, eget volutpat augue. Ghfgop Maecnas cursus fringilla sagittis. Donec eu felis purus, iaculis fringilla ipsum. Inte ger non nulla sem, eget volutpat augue. Curabitur in turpisju massa. Donec et nibh non turpis pellentesque suscipit eget vel odio.  Aliquam consectetur. Fringilla ipsum.           </p>
            <p>
Ringilla ipsum. Donec et nibh non turpis pellentesque suscipit eget vel odio. Sed tempus orci tempus libero suscipit elementum. Aliquam consectetur. Ghfgop Maecnas cursus fringilla sagittis. Donec eu felis purus, iaculis fringi. ipsum. Integer non nulla sem, eget volutpat augue. Ghfgop pelle ntesque suscipit eget consectetur.</p>
          </blockquote>
        </li>
      </ul>
	</div>
    </div>
	</div>


    <div class="col-full">
      <div class="hor_separator hor1"></div>
      <h2 class="head1">Our Best Chefs</h2>
    </div>
    <div class="clear"></div>

	<div class="row">
    <div class="chefs">
      <div class="col-1-4">
	  	<div class="wrap-col">
        <img src="{% static 'img/page2_img3.jpg' %}" alt="" class="img_inner">
        <p class="col1"><a href="#">Ann Franklin</a></p>Nulla pellentesque tempus quam nec porta. Donec nec lorem enim. Aenean velit velit, faucibus sed porta quis, gt er semper ac elit. Aliquam hendrerit mo lestie turpis condimentum tristique. Fty aliquam malesuada orci a massa yht. semper sed interdum arcu
		</div>
      </div>
      <div class="col-1-4">
	  	<div class="wrap-col">
        <img src="{% static 'img/page2_img4.jpg' %}" alt="" class="img_inner">
        <p class="col1"><a href="#"> Milisa Dayemond</a></p>Lorem ipsum pellentesque tempus quam nec porta. Donec nec lorem enim. Aenean velit velit, faucibus sed porta quis, gt er semper ac elit. Aliquam hendrerit mo lestie turpis condimentum tristique. Fty aliquam malesuada orci a massa iaculis. Integer a diam a odio.
		</div>
      </div>
      <div class="col-1-4">
	  	<div class="wrap-col">
        <img src="{% static 'img/page2_img5.jpg' %}" alt="" class="img_inner">
        <p class="col1"><a href="#">Liza Croft</a></p>Aenean velittempus quam nec porta. Donec nec lorem enim. Aenean velit velit, faucibus sed porta quis, gt er semper ac elit. Aliquam hendrerit mo lestie turpis condimentum tristique. Fty aliquam malesuada orci a massa yht. semper sed interdum.
		</div>
      </div>
      <div class="col-1-4">
	  	<div class="wrap-col">
        <img src="{% static 'img/page2_img6.jpg' %}" alt="" class="img_inner">
        <p class="col1"><a href="#">Alan Soares</a></p>Donec necllentesque tempus quam nec porta. Donec nec lorem enim. Aenean velit velit, faucibus sed porta quis, gt er semper ac elit. Aliquam hendrerit mo lestie turpis condimentum tristique. Fty aliquam malesuada orci a massa yht. semper sed interdum.
		</div>
      </div>
    </div>
	</div>

    <div class="row">
    <div class="bottom_block">
      </div>
	  </div>
    </div>
  </div>
</div>



<footer>
    {% include 'restapp/footer.html' %}
    <div class="text-center">
        All Rights Registered by @HeArt Designers
    </div>
</footer>


</body>
</html>

restapp/templates/restapp/contact.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>24 Hours Italian Restaurant</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/slider.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/zerogrid.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css" media="screen">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
    <script src="{% static 'js/superfish.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/sForm.js' %}"></script>
    <script src="{% static 'js/jquery.carouFredSel-6.1.0-packed.js' %}"></script>
    <script src="{% static 'js/tms-0.4.1.js' %}"></script>
    <script src="{% static 'js/css3-mediaqueries.js' %}"></script>

</head>
<body>

<header>
    {% include 'restapp/header.html' %}
</header>

<!--=======content================================-->

<div class="main">
    <div class="content">
        <div class="zerogrid">
            <div class="row">
                <div class="col-2-5">
                    <div class="wrap-col">
                        <h2>Find Us</h2>
                        <div class="map">
                            <figure class="img_inner">
                                <iframe src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Brooklyn,+New+York,+NY,+United+States&amp;aq=0&amp;sll=37.0625,-95.677068&amp;sspn=61.282355,146.513672&amp;ie=UTF8&amp;hq=&amp;hnear=Brooklyn,+Kings,+New+York&amp;ll=40.649974,-73.950005&amp;spn=0.01628,0.025663&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
                            </figure>
                            <address>
                                <dl>
                                    <dt><p>The Company Name Inc.<br>
                                        8901 Marmora Road,<br>
                                        Glasgow, D04 89GR.</p>
                                    </dt>
                                    <dd><span>Freephone:</span>+1 800 559 6580</dd>
                                    <dd><span>Telephone:</span>+1 800 603 6035</dd>
                                    <dd><span>FAX:</span>+1 800 889 9898</dd>
                                </dl>
                            </address>

                        </div>
                    </div>
                </div>
                <div class="col-1-5">
                    <div class="wrap-col"><!--empty--></div>
                </div>
                <div class="col-2-5">
                    <div class="wrap-col">
                        <h2>Contact Us</h2>
                        <form id="form">
                            <div class="success_wrapper">
                                <div class="success">Contact form submitted!<br>
                                    <strong>We will be in touch soon.</strong></div>
                            </div>
                            <fieldset>
                                <label class="name">
                                    <input type="text" placeholder="Enter Your Name">
                                    <br class="clear">
                                    <span class="error error-empty">*This is not a valid name.</span><span
                                        class="empty error-empty">*This field is required.</span> </label>
                                <label class="email">
                                    <input type="text" placeholder="Enter Your Email">
                                    <br class="clear">
                                    <span class="error error-empty">*This is not a valid email address.</span><span
                                        class="empty error-empty">*This field is required.</span> </label>
                                <label class="phone">
                                    <input type="tel" placeholder="Enter Your Phone Number">
                                    <br class="clear">
                                    <span class="error error-empty">*This is not a valid phone number.</span><span
                                        class="empty error-empty">*This field is required.</span> </label>
                                <label class="message">
                                    <textarea placeholder="Message">Message:</textarea>
                                    <br class="clear">
                                    <span class="error">*The message is too short.</span> <span class="empty">*This field is required.</span>
                                </label>
                                <div class="clear"></div>
                                <div class="btns"><a data-type="reset" class="btn">clear</a><a data-type="submit"
                                                                                               class="btn">send</a>
                                    <div class="clear"></div>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="bottom_block">
                    <div class="col-1-2">
                        <h3>Follow Us</h3>
                        <div class="socials">
                            <a href="#"></a>
                            <a href="#"></a>
                            <a href="#"></a>
                        </div>
                    </div>
                    <div class="col-1-2">
                        <h3>Email Updates</h3>
                        <p class="col1">Join our digital mailing list and get news<br> deals and be first to know about
                            events</p>
                        <form id="newsletter">
                            <div class="success text-center">Your subscribe request has been sent!</div>
                            <input type="email" placeholder="Enter e-mail address">
                            <a href="#" class="btn" data-type="submit">subscribe</a>
                            <span class="error">*This is not a valid email address.</span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<footer>
    {% include 'restapp/footer.html' %}
    <div class="text-center">
        All Rights Registered by @HeArt Designers
    </div>
</footer>

</body>
</html>

restapp/templates/restapp/footer.html
<div class="zerogrid">
    <div class="col-full">
        <div class="wrap-col">
            <div class="text-center footer-heading">24 Hours Italian Restaurant</div>
            <br>
            <div class="row">

                <div class="col-md-3">
                    <div><h4><strong>About Italian Restaurant</strong></h4></div>
                    <div>About Restaurant</div>
                    <div>Careers</div>
                </div>

                <div class="col-md-2">
                    <div><h4><strong>Menu</strong></h4></div>
                    <div>Dine@Home Menu</div>
                </div>

                <div class="col-md-2">
                    <div><h4><strong>Privacy</strong></h4></div>
                    <div>Privacy Policy</div>
                    <div>Terms of Use</div>
                </div>

                <div class="col-md-2">
                    <div><h4><strong>Booking</strong></h4></div>
                    <div>Dine@Home</div>
                </div>

                <div class="col-md-2">
                    <div><h4><strong>FAQs</strong></h4></div>
                    <div>Contact Us FAQs</div>
                    <div>Dine@Home FAQs</div>
                    <div>Vouchers FAQs</div>
                    <div>Modern Slavery</div>
                    <div>Statement</div>
                </div>

            </div>
        </div>
    </div>
</div>

restapp/templates/restapp/header.html
{% load static %}

<div class="zerogrid">
        <div class="col-full">
            <div class="wrap-col">
                <h1><a href="{% url 'restapp:index' %}"><img src="{% static 'img/logo.png' %}" alt="EXTERIOR"></a></h1>

                <div class="menu_block">
                    <nav>
                        <ul class="sf-menu">
                            <li class="current"><a href="{% url 'restapp:home' %}">Home</a></li>
                            <!--<li class="with_ul"><a href="#">About Us</a>
                                <ul>
                                    <li><a href="#"> cuisine</a></li>
                                    <li><a href="#">Good rest</a></li>
                                    <li><a href="#">Services</a></li>
                                </ul>
                            </li>-->
                            <li><a href="{% url 'restapp:menu' %}">Menu & Pricing</a></li>
                            <li><a href="{% url 'restapp:about' %}">About</a></li>
                            <li><a href="{% url 'restapp:contact' %}">Contact Us</a></li>
                        </ul>
                    </nav>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>

restapp/templates/restapp/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>24 Hours Italian Restaurant</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/slider.css' %}">
    <link rel="stylesheet" href="{% static 'css/zerogrid.css' %}" type="text/css" media="screen">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css" media="screen">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-1.1.1.js' %}"></script>
    <script src="{% static 'js/superfish.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/sForm.js' %}"></script>
    <script src="{% static 'js/jquery.carouFredSel-6.1.0-packed.js' %}"></script>
    <script src="{% static 'js/tms-0.4.1.js' %}"></script>
    <script src="{% static 'js/css3-mediaqueries.js' %}"></script>
    <script>
      $(window).load(function(){
      $('.slider')._TMS({
              show:0,
              pauseOnHover:false,
              prevBu:'.prev',
              nextBu:'.next',
              playBu:false,
              duration:800,
              preset:'fade',
              pagination:true,//'.pagination',true,'<ul></ul>'
              pagNums:false,
              slideshow:8000,
              numStatus:false,
              banners:false,
          waitBannerAnimation:false,
        progressBar:false
      })
      });

     $(window).load (
    function(){$('.carousel1').carouFredSel({auto: false,prev: '.prev',next: '.next', width: 960, items: {
      visible : {min: 1,
       max: 4
},
height: 'auto',
 width: 240,

    }, responsive: false,

    scroll: 1,

    mousewheel: false,

    swipe: {onMouse: false, onTouch: false}});


    });








    </script>


</head>
<body>

<header>
    {% include 'restapp/header.html' %}
</header>

<!--=======slider================================-->

<div class="main">
    <div class="slider-relative">
        <div class="slider-block">
            <div class="slider">
                <ul class="items">
                    <li><img src="{% static 'img/slide.jpg' %}" alt=""></li>
                    <li><img src="{% static 'img/slide1.jpg' %}" alt=""></li>
                    <li class="mb0"><img src="{% static 'img/slide2.jpg' %}" alt=""></li>
                </ul>


            </div>

        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <button class="btn btn-primary pos new-btn"><strong>Timings</strong></button>
                <button class="btn btn-primary pos new-btn"><strong>Order Online</strong></button>
                <button class="btn btn-primary pos new-btn"><strong>View Menu</strong></button>
            </div>
        </div>
    </div>
    <!--=======content================================-->

    <div class="content page1">
        <div class="zerogrid">
            <div class="row">
                <div class="col-md-6 text-center">
                    <h2>Dine@Home Menu</h2>
                    <div><img class="img-thumbnail bx" src="{% static 'img/page1_img1.jpg' %}" style="height: 200px;"
                              alt="RecipeImage">
                        <div class="col1 upp"><a href="#">kim Lorem ipsum doamet consectet</a></div>
                        <span>Enjoyhe comfort of your own sofa with our our delicious Dine@Home menu. Plus, get 20% off your total bill when you order via Click & Collect!</span>
                        <div class="price">45$</div>
                    </div>
                </div>

                <div class="col-md-6 text-center">
                    <h2>Keeping You Safe</h2>
                    <div><img class="img-thumbnail bx" src="{% static 'img/page1_img1.jpg' %}" style="height: 200px;" alt="RecipeImage">
                        <div class="col1 upp"><a href="#">kim Lorem ipsum doamet consectet</a></div>
                        <span>We’re proud to b our customers and teams safe is our number one priority. Click below for more details.</span>
                        <div class="price">45$</div>
                    </div>
                </div>
            </div>
            <div class="col-full">
                <div class="hor_separator"></div>
            </div>
            <div class="row">
                <div class="col-md-6 text-center">
                    <h2>Health Hub</h2>
                    <div><img class="img-thumbnail bx" src="{% static 'img/page1_img1.jpg' %}" style="height: 200px;"
                              alt="RecipeImage">
                        <div class="col1 upp"><a href="#">kim Lorem ipsum doamet consectet</a></div>
                        <span>We all want to . So whether you’re vegan, vegetarian, flexitarian or gluten free, we are committed to making sure you have all the information you need.</span>
                        <div class="price">45$</div>
                    </div>
                </div>

                <div class="col-md-6 text-center">
                    <h2>Mother's Day Special</h2>
                    <div><img class="img-thumbnail bx" src="{% static 'img/page1_img1.jpg' %}" style="height: 200px;"
                               alt="RecipeImage">

                        <div class="col1 upp"><a href="#">kim Lorem ipsum doamet consectet</a></div>
                        <span>Dine at home with us  with amazing bundle deals for everyone and a new special - creamy King Prawn & Pancetta Spaghetti! Available Friday 12th - Sunday 14th March.</span>
                        <div class="price">45$</div>
                    </div>
                </div>
            </div>
            <!--  <div class="col-md-6">
                  <div class="wrap-col">
                      <h2>Dine@Home Menu</h2>
                      <div class="page1_block col1">
                          <div class="col-md-12"><img src="{% static 'img/welcome_img.jpg' %}" alt=""></div>
                          <div class="col-md-12">
                              <div class="extra_wrapper">
                                  <p><span class="col2"><a
                                          href="http://blog.templatemonster.com/free-website-templates/"
                                          rel="nofollow">Click here</a></span> for more info about this free website
                                      template created by TemplateMonster.com </p>
                                  Aenean nonummy hendrerit mau rellus porta. Fusce suscipit varius m sociis natoque
                                  penaibet magni parturient montes nasetur ridiculumula dui. <br>
                                  <a href="#" class="btn btn-primary">more</a>
                              </div>
                          </div>
                          <div class="clear"></div>
                      </div>
                  </div>
              </div>   -->
            <!-- <div class="col-md-6">
                 <div class="wrap-col">
                     <h2>Features</h2>
                     <ul class="list">
                         <li><a href="#">Unlimited consultations and/or planning</a></li>
                         <li><a href="#">Expert advice on traditions, customs, aetiquette</a></li>
                         <li><a href="#">Determine and stay within budget</a></li>
                         <li><a href="#">Choosing the right Wedding Venue</a></li>
                         <li><a href="#">Provide preferred vendor's list</a></li>
                         <li><a href="#">Assist with wedding scheme and design</a></li>
                     </ul>
                 </div>
             </div>-->

            <div class="col-full">
                <div class="hor_separator"></div>
            </div>
            <div class="row">
                <div class="col-full">
                    <div class="wrap-col">
                        <div class="car_wrap">
                            <h2>Best Choice</h2>
                            <a href="#" class="prev"></a><a href="#" class="next"></a>
                            <ul class="carousel1">
                                <li>
                                    <div><img src="{% static 'img/page1_img1.jpg' %}" alt="">
                                        <div class="col1 upp"><a href="#">kim Lorem ipsum doamet consectet</a></div>
                                        <span> Dorem ipsum dolor amet consectetur</span>
                                        <div class="price">45$</div>
                                    </div>
                                </li>
                                <li>
                                    <div><img src="{% static 'img/page1_img2.jpg' %}" alt="">
                                        <div class="col1 upp"><a href="#">Lorem ipsum doamet consectet</a></div>
                                        <span> Dorem ipsum dolor amet consectetur</span>
                                        <div class="price">45$</div>
                                    </div>
                                </li>
                                <li>
                                    <div><img src="{% static 'img/page1_img3.jpg' %}" alt="">
                                        <div class="col1 upp"><a href="#">Lorem ipsum doamet consectet</a></div>
                                        <span> Dorem ipsum dolor amet consectetur</span>
                                        <div class="price">45$</div>
                                    </div>
                                </li>
                                <li>
                                    <div><img src="{% static 'img/page1_img4.jpg' %}" alt="">
                                        <div class="col1 upp"><a href="#">Lorem ipsum doamet consectet</a></div>
                                        <span> Dorem ipsum dolor amet consectetur</span>
                                        <div class="price">45$</div>
                                    </div>
                                </li>
                                <li>
                                    <div><img src="{% static 'img/page1_img3.jpg' %}" alt="">
                                        <div class="col1 upp"><a href="#">Lorem ipsum doamet consectet kim</a></div>
                                        <span> Dorem ipsum dolor amet consectetur</span>
                                        <div class="price">45$</div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<footer>
    {% include 'restapp/footer.html' %}
    <div class="text-center">
        All Rights Registered by @HeArt Designers
    </div>
</footer>

</body>
</html>